--****************************************************************************
--CRIA UMA TABELA TEMPORARIA PARA IMPORTAÇÃO DO ARQUIVO DE SAIDA DO VISTA
IF OBJECT_ID('tempdb..#tempTable') IS NOT NULL 
    DROP TABLE #tempTable
CREATE TABLE #tempTable (
  RowVal VarChar(Max)
  )

GO 
 
--****************************************************************************
--IMPORTA TODOS OS DADOS DO ARQUIVO DUMP DO VISTA PARA A TABELA TEMPORARIA
BULK INSERT #tempTable
FROM 'C:\DUMP\DUMP_DADOS_0328-SW10.asc' 
WITH (
    FIRSTROW = 32,
    ROWTERMINATOR = '\n'
)

GO
--SELECT * FROM #tempTable
--DROP TABLE #tempTable

--****************************************************************************
--               INSERE OS DADOS NA TABELA DE ESTATISTICA
DECLARE @TableVar TABLE(CHANNEL_NO	SMALLINT); 
INSERT INTO TB_ESTATISTICA (
	RECORDED_YEAR,	RECORDED_DAY, RECORDED_HOUR, RECORDED_MINUTE, RECORDED_SECOND,		
	SHOTLINE_NUMBER,SHOT_POINT_NO,		
	RECEIVERLINE_NUMBER, FIELD_STATION_NUMBER,
	XREC, YREC, ELEV_REC,
	XSHOT, YSHOT, ELEV_SHOT,			
	TILTERROR,
	RESISTERROR,	
	LEAKAGEERROR,
	FIELD_RECORD_NO,		
	SWATH_ID,			
	DATA_RMSAMPLITUDE,
	DEFECTIVE_TRACE,			
	CHANNEL_NO,
	DEAD_TRACE,			
	LIVE_TRACE,			
	DATA_MAXFREQ,
	DATA_MAXABSAMPLITUDE,
	ANOM_FREQ,
	ANOM_AMP,
	NOISE_RMSAMPLITUDE,
	AMB_NOISE_UP_LIMIT)
	OUTPUT INSERTED.CHANNEL_NO INTO @TableVar(CHANNEL_NO)			
	SELECT 
	   CAST(SubString(RowVal,1,4)    AS SMALLINT)		As RECORDED_YEAR,	
	   CAST(SubString(RowVal,5,4)    AS SMALLINT)		As RECORDED_DAY,	
	   CAST(SubString(RowVal,9,2)    AS TINYINT)		As RECORDED_HOUR,	
	   CAST(SubString(RowVal,11,2)   AS TINYINT)		As RECORDED_MINUTE,
	   CAST(SubString(RowVal,13,2)   AS TINYINT)		As RECORDED_SECOND,
	   CAST(SubString(RowVal,18,4)   AS INT)			As SHOTLINE_NUMBER,
	   CAST(SubString(RowVal,22,4)   AS INT)			As SHOT_POINT_NO,	
	   CAST(SubString(RowVal,26,4)   AS INT)			As RECEIVERLINE_NUMBER,
	   CAST(SubString(RowVal,30,4)   AS INT)			As FIELD_STATION_NUMBER,
	   CAST(SubString(RowVal,35,11)  AS DECIMAL(10,2))	As XREC,	
	   CAST(SubString(RowVal,46,11)  AS DECIMAL(10,2))	As YREC, 
	   CAST(SubString(RowVal,57,6)   AS DECIMAL( 6,2))	As ELEV_REC,
	   CAST(SubString(RowVal,63,11)  AS DECIMAL(10,2))	As XSHOT,
	   CAST(SubString(RowVal,74,11)  AS DECIMAL(10,2))	As YSHOT,
	   CAST(SubString(RowVal,85,6)   AS DECIMAL( 6,2))	As ELEV_SHOT, 
	   CAST(SubString(RowVal,91,2)   AS TINYINT)		As TRCHDR3_TILTERROR,
	   CAST(SubString(RowVal,93,2)   AS TINYINT)		As TRCHDR3_RESISTERROR,
	   CAST(SubString(RowVal,95,2)   AS TINYINT)		As TRCHDR5_LEAKAGEERROR,
	   CAST(SubString(RowVal,97,6)   AS INT)			As FIELD_RECORD_NO,
	   CAST(SubString(RowVal,103,4)  AS SMALLINT)		As SWATH_ID,
	   CAST(SubString(RowVal,109,17) AS DECIMAL(20,8))	As DATA_RMSAMPLITUDE,
	   CAST(SubString(RowVal,127,2)  AS TINYINT)		As TRACO_DEFEITUOSO, 
	   CAST(SubString(RowVal,129,11) AS SMALLINT)		As CHANNEL_NO,
	   CAST(SubString(RowVal,140,3)  AS TINYINT)		As TRACO_MORTO,
	   CAST(SubString(RowVal,144,3)  AS TINYINT)		As TRAVO_VIVO,
	   CAST(SubString(RowVal,148,8)  AS DECIMAL(8,3))	As DATA_MAXFREQ,
	   CAST(SubString(RowVal,156,15) AS DECIMAL(20,8))	As DATA_MAXABSAMPLITUDE,
	   CAST(SubString(RowVal,172,2)  AS TINYINT)		As ANOM_FREQ,
	   CAST(SubString(RowVal,174,2)  AS TINYINT)		As ANOM_AMP,
	   CAST(SubString(RowVal,176,15) AS DECIMAL(20,8))	As NOISE_RMSAMPLITUDE,
	   CAST(SubString(RowVal,192,2)  AS TINYINT)		As AMB_NOISE_UP_LIMIT
	FROM 
	  #tempTable
--INSERE UM REGISTRO NA TABELA DE CONTROLE DE IMPORTACAO
	INSERT INTO TB_CONTROL_IMPORT
		(DATA_IMPORT,QTDE,TIPO_IMPORTED)
	 SELECT GETDATE(), COUNT(CHANNEL_NO),'TRACES' FROM @TableVar

--SELECT * FROM TB_ESTATISTICA
--SELECT * FROM TB_SWATH 
--SELECT * FROM TB_CONTROL_IMPORT
--DELETE FROM TB_ESTATISTICA 
--DROP TABLE TB_CONTROL_IMPORT

SELECT TOP 1 QTDE FROM TB_CONTROL_IMPORT ORDER BY IMPORT_ID DESC
/*
SELECT 
	   CAST(SubString(RowVal,1,4)    AS SMALLINT)		As RECORDED_YEAR,	
	   CAST(SubString(RowVal,5,4)    AS SMALLINT)		As RECORDED_DAY,	
	   CAST(SubString(RowVal,9,2)    AS TINYINT)		As RECORDED_HOUR,	
	   CAST(SubString(RowVal,11,2)   AS TINYINT)		As RECORDED_MINUTE,
	   CAST(SubString(RowVal,13,2)   AS TINYINT)		As RECORDED_SECOND,
	   CAST(SubString(RowVal,18,4)   AS INT)			As SHOTLINE_NUMBER,
	   CAST(SubString(RowVal,22,4)   AS INT)			As SHOT_POINT_NO,	
	   CAST(SubString(RowVal,26,4)   AS INT)			As RECEIVERLINE_NUMBER,
	   CAST(SubString(RowVal,30,4)   AS INT)			As FIELD_STATION_NUMBER,
	   CAST(SubString(RowVal,35,11)  AS DECIMAL(10,2))	As XREC,	
	   CAST(SubString(RowVal,46,11)  AS DECIMAL(10,2))	As YREC, 
	   CAST(SubString(RowVal,57,6)   AS DECIMAL( 6,2))	As ELEV_REC,
	   CAST(SubString(RowVal,63,11)  AS DECIMAL(10,2))	As XSHOT,
	   CAST(SubString(RowVal,74,11)  AS DECIMAL(10,2))	As YSHOT,
	   CAST(SubString(RowVal,85,6)   AS DECIMAL( 6,2))	As ELEV_SHOT, 
	   CAST(SubString(RowVal,91,2)   AS TINYINT)		As TRCHDR3_TILTERROR,
	   CAST(SubString(RowVal,93,2)   AS TINYINT)		As TRCHDR3_RESISTERROR,
	   CAST(SubString(RowVal,95,2)   AS TINYINT)		As TRCHDR5_LEAKAGEERROR,
	   CAST(SubString(RowVal,97,6)   AS INT)			As FIELD_RECORD_NO,
	   CAST(SubString(RowVal,103,4)  AS SMALLINT)		As SWATH_ID,
	   CAST(SubString(RowVal,109,17) AS DECIMAL(15,8))	As DATA_RMSAMPLITUDE,
	   CAST(SubString(RowVal,127,2)  AS TINYINT)		As TRACO_DEFEITUOSO, 
	   CAST(SubString(RowVal,129,11) AS SMALLINT)		As CHANNEL_NO,
	   CAST(SubString(RowVal,140,3)  AS TINYINT)		As TRACO_MORTO,
	   CAST(SubString(RowVal,144,3)  AS TINYINT)		As TRAVO_VIVO,
	   CAST(SubString(RowVal,148,8)  AS DECIMAL(8,3))	As DATA_MAXFREQ,
	   CAST(SubString(RowVal,156,15) AS DECIMAL(15,8))	As DATA_MAXABSAMPLITUDE,
	   CAST(SubString(RowVal,172,2)  AS TINYINT)		As ANOM_FREQ,
	   CAST(SubString(RowVal,174,2)  AS TINYINT)		As ANOM_AMP,
	   CAST(SubString(RowVal,176,15) AS DECIMAL(15,8))	As NOISE_RMSAMPLITUDE,
	   CAST(SubString(RowVal,192,2)  AS TINYINT)		As AMB_NOISE_UP_LIMIT
	FROM 
	  #tempTable

*/