/* 
	DATA BASE FOR STATISC QUALITY CONTROL OF ONSHORE SEISMIC DATA ACQUISITIOM 
	
	AUTHOR: EMERSON ALVES DA SILVA
    
 */


--CREATE THE DATA BASE
CREATE DATABASE ONSHORE_QC_SEISMIC
USE ONSHORE_QC_SEISMIC


--CREATE THE TABE SWATH RESUME 
CREATE TABLE TB_SWATH (
	SWATH_ID				SMALLINT		NOT NULL,
	QTDE_SP					INT				NOT NULL,
	MIN_RL					INT				NOT NULL,
	MAX_RL					INT				NOT NULL,
	MIN_ER					INT				NOT NULL,
	MAX_ER					INT				NOT NULL,
	MIN_SL					INT				NOT NULL,
	MAX_SL					INT				NOT NULL,
	MIN_SP					INT				NOT NULL,
	MAX_SP					INT				NOT NULL

	CONSTRAINT PK_TB_SWATH_SWATH_ID PRIMARY KEY (SWATH_ID)
	)

GO
--ALTER TABLE TB_SWATH ADD QTDE_SP INT	


/*                         FORMAT OF FILE THAT WILL BE IMPORTERD 
# RECORDED_YEAR                  Col:     1 -     4 Decs:   0 Mult: 1.000000  
# RECORDED_DAY                   Col:     5 -     8 Decs:   0 Mult: 1.000000  
# RECORDED_HOUR                  Col:     9 -    10 Decs:   0 Mult: 1.000000  
# RECORDED_MINUTE                Col:    11 -    12 Decs:   0 Mult: 1.000000  
# RECORDED_SECOND                Col:    13 -    14 Decs:   0 Mult: 1.000000  
# SHOTLINE_NUMBER                Col:    18 -    21 Decs:   0 Mult: 1.000000  
# SHOT_POINT_NO                  Col:    22 -    25 Decs:   0 Mult: 1.000000  
# RECEIVERLINE_NUMBER            Col:    26 -    29 Decs:   0 Mult: 1.000000  
# FIELD_STATION_NUMBER           Col:    30 -    33 Decs:   0 Mult: 1.000000  
# XREC                           Col:    35 -    45 Decs:   2 Mult: 1.000000  
# YREC                           Col:    46 -    56 Decs:   2 Mult: 1.000000  
# ELEV_REC                       Col:    57 -    62 Decs:   2 Mult: 1.000000  
# XSHOT                          Col:    63 -    73 Decs:   2 Mult: 1.000000  
# YSHOT                          Col:    74 -    84 Decs:   2 Mult: 1.000000  
# ELEV_SHOT                      Col:    85 -    90 Decs:   2 Mult: 1.000000  
# TRCHDR3_TILTERROR              Col:    91 -    92 Decs:   0 Mult: 1.000000  
# TRCHDR3_RESISTERROR            Col:    93 -    94 Decs:   0 Mult: 1.000000  
# TRCHDR5_LEAKAGEERROR           Col:    95 -    96 Decs:   0 Mult: 1.000000  
# FIELD_RECORD_NO                Col:    97 -   102 Decs:   0 Mult: 1.000000  
# EXTHDR_SWATHID                 Col:   103 -   106 Decs:   0 Mult: 1.000000  
# DATA_RMSAMPLITUDE              Col:   109 -   125 Decs:   8 Mult: 10000.000000  
# VWUSER_1                       Col:   127 -   128 Decs:   0 Mult: 1.000000  
# CHANNEL_NO                     Col:   129 -   139 Decs:   0 Mult: 1.000000  
# VWUSER_7                       Col:   140 -   142 Decs:   0 Mult: 1.000000  
# VWUSER_8                       Col:   144 -   146 Decs:   0 Mult: 1.000000  
# DATA_MAXFREQ                   Col:   148 -   155 Decs:   3 Mult: 1.000000  
# DATA_MAXABSAMPLITUDE           Col:   156 -   170 Decs:   5 Mult: 10000.000000  
# VWUSER_11                      Col:   172 -   173 Decs:   0 Mult: 1.000000  
# VWUSER_12                      Col:   174 -   175 Decs:   0 Mult: 1.000000  
# VWUSER_22                      Col:   176 -   190 Decs:   8 Mult: 10000.000000  
# VWUSER_9                       Col:   192 -   193 Decs:   0 Mult: 1.000000  
*/
--CREATE THE STATISTIC TABLE
CREATE TABLE TB_ESTATISTICA (
	RECORDED_YEAR			SMALLINT		NOT NULL,
	RECORDED_DAY			SMALLINT		NOT NULL,
	RECORDED_HOUR			TINYINT			NOT NULL,
	RECORDED_MINUTE			TINYINT			NOT NULL,
	RECORDED_SECOND			TINYINT			NOT NULL,
	SHOTLINE_NUMBER			INT				NOT NULL,
	SHOT_POINT_NO			INT				NOT NULL,
	RECEIVERLINE_NUMBER		INT				NOT NULL,
	FIELD_STATION_NUMBER	INT				NOT NULL,
	XREC					DECIMAL(10,2) 	NOT NULL,
	YREC					DECIMAL(10,2) 	NOT NULL,
	ELEV_REC				DECIMAL(6,2) 	NOT NULL,
	XSHOT					DECIMAL(10,2) 	NOT NULL,
	YSHOT					DECIMAL(10,2) 	NOT NULL,
	ELEV_SHOT				DECIMAL(6,2) 	NOT NULL,
	TILTERROR				TINYINT			NOT NULL,
	RESISTERROR				TINYINT			NOT NULL,
	LEAKAGEERROR			TINYINT			NOT NULL,
	FIELD_RECORD_NO			INT				NOT NULL,
	SWATH_ID				SMALLINT		NOT NULL,
	DATA_RMSAMPLITUDE       DECIMAL(20,8)	NOT NULL,
	DEFECTIVE_TRACE			TINYINT			NOT NULL,
	CHANNEL_NO				SMALLINT		NOT NULL,
	DEAD_TRACE				TINYINT			NOT NULL,
	LIVE_TRACE				TINYINT			NOT NULL,
	DATA_MAXFREQ			DECIMAL(8,3)    NOT NULL,
	DATA_MAXABSAMPLITUDE	DECIMAL(20,8)	NOT NULL,
	NOISE_RMSAMPLITUDE		DECIMAL(20,8)	NOT NULL,
	ANOM_FREQ				TINYINT			NOT NULL,
	ANOM_AMP				TINYINT			NOT NULL,
	AMB_NOISE_UP_LIMIT		TINYINT			NOT NULL

	CONSTRAINT PK_TB_ESTATISTICA_GROUP_FIELD PRIMARY KEY (SWATH_ID, SHOTLINE_NUMBER, SHOT_POINT_NO, FIELD_RECORD_NO, CHANNEL_NO)
	
	CONSTRAINT FK_TB_ESTATISTIC_SWATH_ID FOREIGN KEY (SWATH_ID)
	REFERENCES TB_SWATH(SWATH_ID)
	)

--CREATE THE TABLE OF DEAD STATIONS
CREATE TABLE TB_ER_MORTAS (
	RECEIVERLINE_NUMBER		INT				NOT NULL,
	FIELD_STATION_NUMBER	INT				NOT NULL,
	MOTIVO					VARCHAR(50)		NOT NULL

	CONSTRAINT PK_TB_ER_MORTAS PRIMARY KEY (RECEIVERLINE_NUMBER,FIELD_STATION_NUMBER)
	)


--CREATE THE TABLE LOG OF IMPORT FILE
CREATE TABLE TB_CONTROL_IMPORT (
	IMPORT_ID		INT		IDENTITY,
	DATA_IMPORT		DATETIME,	
	QTDE			INT,
	TIPO_IMPORTED   VARCHAR(10) 		
	
	CONSTRAINT PK_TB_CONTROL_IMPORT_IMPORT_ID PRIMARY KEY (IMPORT_ID)
	)

--DROP TABLE TB_CONTROL_IMPORT

--DROP TABLE TB_OBSERVER_REPORT

--CREATE THE OBSERVER REPORT TABLE
CREATE TABLE TB_OBSERVER_REPORT (
	FIELD_RECORD_NO		INT			NOT NULL,
--	SHOT_INDEX			INT,
	SWATH_ID			SMALLINT	NOT NULL,
	BLASTER_ID			SMALLINT,
	SHOT_TIME			TIME,
	SHOT_DATE			DATE,
	UPHOLE_TIME			DECIMAL(6,2),
	SHOTLINE_NUMBER		INT,
	SHOT_POINT_NO		INT,
--	POINT_INDEX			SMALLINT,
--	XSHOT				DECIMAL(10,2),
--	YSHOT				DECIMAL(10,2),
--	ELEV_SHOT			DECIMAL(6,2), 
	SFL					INT,
	SFN					INT,
--	SPREAD_ID			SMALLINT,
	PROCESS_TYPE		VARCHAR(20),
--	PILOT_LENGTH		SMALLINT,
	COMMENT				VARCHAR(100),
--	SWEEP_LENGTH		SMALLINT,
--	SRC_SET_ID			SMALLINT,
	NB_OF_LIVE_SEIS		SMALLINT,
--	MAX_OF_MAX_SEIS		DECIMAL(8,2), 
--	HIST_ZEROING_LENGTH	VARCHAR(15),
	RECORD_TYPE			VARCHAR(15),
--	LIVE_SEIS			VARCHAR(100),
--	DEAD_SEIS			VARCHAR(100),
--	ACQ_ERROR			VARCHAR(10),
	ITB					BIT,
	BLASTER_SHOT_STATUS	TINYINT
--	TYPE_OF_TEST		VARCHAR(10)

	CONSTRAINT PK_TB_OBSERVER_REPORT_FFID PRIMARY KEY (FIELD_RECORD_NO)
	
	CONSTRAINT FK_TB_OBSERVER_REPORT_SWATH_ID FOREIGN KEY (SWATH_ID)
	REFERENCES TB_SWATH(SWATH_ID)
)

--MELHORAR ESTA TABELA
--CREATE THE POSTPOLOT SHOT TABLE
CREATE TABLE TB_POSTPLOT_SHOT (
	SHOTLINE_NUMBER						INT	NOT NULL,
	SHOT_POINT_NO						INT	NOT NULL,
	OFFSETSONDA_SHOTLINE_NUMBER			INT,				
	OFFSETSONDA_SHOT_POINT_NO			INT,	
	OFFSETLOAD_SHOTLINE_NUMBER			INT,
	OFFSETLOAD_SHOT_POINT_NO			INT,

	CONSTRAINT PK_TB_POSTPLOT_SHOT_SL_SP PRIMARY KEY (SHOTLINE_NUMBER,SHOT_POINT_NO)
	)

--CREATE THE POSTPLOT RECEIVERS TABLE
CREATE TABLE TB_POSTPLOT_REC (
	RECEIVERLINE_NUMBER		INT				NOT NULL,
	FIELD_STATION_NUMBER	INT				NOT NULL,
	PRE_LOCAL_EAST			DECIMAL(12,3),	 
	PRE_LOCAL_NORTH			DECIMAL(12,3),  	 
	STATION_LOCATED  		INT,
	POS_LOCAL_EAST			DECIMAL(12,3),
	POS_LOCAL_NORTH			DECIMAL(12,3),
	POS_LOCAL_HEIGHT		DECIMAL(7,3),
	OFFSET_NORTH			DECIMAL(7,3),
	OFFSET_EAST				DECIMAL(7,3),
	OFFSET_RANGE			DECIMAL(7,3),
	COMMENT					VARCHAR(30),
	SURVEY_LOCAL_TIME		VARCHAR(20),
	LAT						VARCHAR(15),
	LONG					VARCHAR(15)
	
	CONSTRAINT PK_TB_POSTPLOT_REC_RL_ST PRIMARY KEY (RECEIVERLINE_NUMBER,FIELD_STATION_NUMBER)
)