SELECT TB_TRACOS.SWATH_ID, TB_PT.PT_VALIDOS,
	   TB_TRACOS.ATIVOS, TB_TRACOS.DEFEITUOSOS,
	   TB_TRACOS.MORTOS, TB_TRACOS.TILT_ERROR,
	   TB_TRACOS.RESIST_ERROR, TB_TRACOS.LEAK_ERROR,
       TB_TRACOS.RUIDO_AMB,TB_TRACOS.ANOM_FREQ, TB_TRACOS.ANOM_AMP,
	   TB_QT_SENSORERR.QtdSensorErr,TB_TOT_ANOM.TOT_ANOM,
	   COALESCE(QT_PT_RS,0) AS QT_PT_RAZAO_RS,TB_TOTER.TOT_ER,TB_RS_TRACO.QT_TRC_RAZAO_RS 
	FROM (
		SELECT SWATH_ID, 
				COUNT(SWATH_ID)					AS ATIVOS, 
				SUM(DEFECTIVE_TRACE)			AS DEFEITUOSOS,
				SUM(DEAD_TRACE)					AS MORTOS,
				SUM(TILTERROR)					AS TILT_ERROR,
				SUM(RESISTERROR)				AS RESIST_ERROR,
				SUM(LEAKAGEERROR)				AS LEAK_ERROR,
				SUM(AMB_NOISE_UP_LIMIT)			AS RUIDO_AMB,
				SUM(ANOM_FREQ)					AS ANOM_FREQ,
				SUM(ANOM_AMP)					AS ANOM_AMP
			FROM TB_ESTATISTICA 
			GROUP BY SWATH_ID 
			) AS TB_TRACOS 
	INNER JOIN (
			SELECT SWATH_ID, COUNT(SHOT_POINT_NO) AS PT_VALIDOS 
				FROM TB_OBSERVER_REPORT 
				GROUP BY SWATH_ID 
				) AS TB_PT
	ON TB_TRACOS.SWATH_ID = TB_PT.SWATH_ID 
	INNER JOIN (
		SELECT SWATH_ID, COUNT(*) AS QtdSensorErr 
		   FROM TB_ESTATISTICA
			  WHERE (TILTERROR+RESISTERROR+LEAKAGEERROR) >0
			  GROUP BY  SWATH_ID) AS TB_QT_SENSORERR
	ON  TB_TRACOS.SWATH_ID =TB_QT_SENSORERR.SWATH_ID
	INNER JOIN (
		SELECT SWATH_ID, COUNT(*) AS TOT_ANOM FROM TB_ESTATISTICA 
			WHERE ANOM_AMP+ANOM_FREQ>0
			GROUP BY SWATH_ID 
	) AS TB_TOT_ANOM
	ON TB_TRACOS.SWATH_ID =TB_TOT_ANOM.SWATH_ID
	LEFT JOIN (
		SELECT	SWATH_ID,COUNT(RAZAO_RS) AS QT_PT_RS 
		FROM (
			SELECT SWATH_ID,TB_SWFFID.FIELD_RECORD_NO,RAZAO_RS FROM (
				SELECT FIELD_RECORD_NO,
							ABS(SUM(NOISE_RMSAMPLITUDE) /	
					SUM(DATA_RMSAMPLITUDE-NOISE_RMSAMPLITUDE)) AS RAZAO_RS
					FROM TB_ESTATISTICA 
					GROUP BY FIELD_RECORD_NO) TB_RSFFID
			INNER JOIN (
				SELECT SWATH_ID,FIELD_RECORD_NO FROM TB_OBSERVER_REPORT  
					) AS TB_SWFFID
				ON TB_SWFFID.FIELD_RECORD_NO = TB_RSFFID.FIELD_RECORD_NO 
			) AS TB_RS_TRACO
		WHERE RAZAO_RS>1
		GROUP BY SWATH_ID
		) AS TB_RS_PT 		
	ON TB_TRACOS.SWATH_ID =TB_RS_PT.SWATH_ID
	INNER JOIN (
		SELECT SWATH_ID, COUNT(*) AS TOT_ER FROM (
				SELECT DISTINCT SWATH_ID, 
							RECEIVERLINE_NUMBER,
							FIELD_STATION_NUMBER   
				FROM TB_ESTATISTICA ) AS TB_TEMPER
			GROUP BY SWATH_ID) AS TB_TOTER 	
	ON TB_TRACOS.SWATH_ID =TB_TOTER.SWATH_ID
	LEFT JOIN (
		SELECT	SWATH_ID,COUNT(TRC_RAZAO_RS) AS QT_TRC_RAZAO_RS 
				FROM (
					SELECT * FROM (	
						 SELECT SWATH_ID,FIELD_RECORD_NO,
						--  CALCULO DA RAZAO RUIDO/SINAL	
	   							IIF(DATA_RMSAMPLITUDE=NOISE_RMSAMPLITUDE,
									(NOISE_RMSAMPLITUDE/DATA_RMSAMPLITUDE),
								(ABS(NOISE_RMSAMPLITUDE/(DATA_RMSAMPLITUDE-NOISE_RMSAMPLITUDE))))	AS TRC_RAZAO_RS
						FROM TB_ESTATISTICA 
						WHERE LIVE_TRACE =1 
					) AS TB_RS_TRACO
					WHERE TRC_RAZAO_RS>1) AS TB_FIM_RS_TRACO
				GROUP BY SWATH_ID) AS TB_RS_TRACO
	ON TB_TRACOS.SWATH_ID=TB_RS_TRACO.SWATH_ID
	ORDER BY TB_TRACOS.SWATH_ID
